on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
            
       - name: Setup Git
         env:        
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
         run: git config --global user.name $GIT_USER && git config --global user.email $GIT_EMAIL
      # - name: Get latest tag

      # - name: Analyse commit message

      # - name: Determine new version

      # - name: Create new tag

      # - name: Show new version